### ISSUE TITLE
Tried to run configure

### ISSUE THREAD

**Issue by robin-raymond** [peters/curl-for-windows#7]
I did the recursive pull, installed Python 2.7.x (latest) and got this when I ran the scripts:

```
  File "C:\Python27\lib\multiprocessing\forking.py", line 358, in get_command_line
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
is not going to be frozen to produce a Windows executable.''')
RuntimeError:
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 495, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\Users\Robin\Documents\curl-for-windows\configure.py", line 115, in <module>
    run_gyp(gyp_args)
  File "C:\Users\Robin\Documents\curl-for-windows\configure.py", line 101, in run_gyp
    rc = gyp.main(args)
  File "C:\Users\Robin\Documents\curl-for-windows\build\gyp\pylib\gyp\__init__.py", line 525, in main
    return gyp_main(args)
  File "C:\Users\Robin\Documents\curl-for-windows\build\gyp\pylib\gyp\__init__.py", line 501, in gyp_main
    params, options.check, options.circular_check)
  File "C:\Users\Robin\Documents\curl-for-windows\build\gyp\pylib\gyp\__init__.py", line 129, in Load
Traceback (most recent call last):
      File "<string>", line 1, in <module>
params['parallel'], params['root_targets'])
  File "C:\Users\Robin\Documents\curl-for-windows\build\gyp\pylib\gyp\input.py", line 2730, in Load
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 495, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\Users\Robin\Documents\curl-for-windows\configure.py", line 115, in <module>
    check, generator_input_info)
      File "C:\Users\Robin\Documents\curl-for-windows\build\gyp\pylib\gyp\input.py", line 596, in LoadTargetBuildFilesParallel
run_gyp(gyp_args)
  File "C:\Users\Robin\Documents\curl-for-windows\configure.py", line 101, in run_gyp
    parallel_state.pool = multiprocessing.Pool(multiprocessing.cpu_count())
      File "C:\Python27\lib\multiprocessing\__init__.py", line 232, in Pool
rc = gyp.main(args)
      File "C:\Users\Robin\Documents\curl-for-windows\build\gyp\pylib\gyp\__init__.py", line 525, in main
return Pool(processes, initializer, initargs, maxtasksperchild)
  File "C:\Python27\lib\multiprocessing\pool.py", line 159, in __init__
    self._repopulate_pool()
  File "C:\Python27\lib\multiprocessing\pool.py", line 223, in _repopulate_pool
        return gyp_main(args)
w.start()
  File "C:\Users\Robin\Documents\curl-for-windows\build\gyp\pylib\gyp\__init__.py", line 501, in gyp_main
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
        params, options.check, options.circular_check)
self._popen = Popen(self)
  File "C:\Users\Robin\Documents\curl-for-windows\build\gyp\pylib\gyp\__init__.py", line 129, in Load
  File "C:\Python27\lib\multiprocessing\forking.py", line 258, in __init__
    params['parallel'], params['root_targets'])
      File "C:\Users\Robin\Documents\curl-for-windows\build\gyp\pylib\gyp\input.py", line 2730, in Load
cmd = get_command_line() + [rhandle]
  File "C:\Python27\lib\multiprocessing\forking.py", line 358, in get_command_line
    check, generator_input_info)
  File "C:\Users\Robin\Documents\curl-for-windows\build\gyp\pylib\gyp\input.py", line 596, in LoadTargetBuildFilesParallel
    is not going to be frozen to produce a Windows executable.''')
    RuntimeErrorparallel_state.pool = multiprocessing.Pool(multiprocessing.cpu_count())
:   File "C:\Python27\lib\multiprocessing\__init__.py", line 232, in Pool

                Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.return Pool(processes, initializer, initargs, maxtasksperchild)
```

I'm not a python expert to know what to do here... FYI - VS2013 on Win8.1

**Comment by consp** [comment]
This can be fixed by disabeling parallel support in gyp, either by command line arguments in configure.py or by editing 
build/gyp/pylib/gyp/**init**.py line 392 into 
options.parallel = False
